Iss1b
PSY6983-2021/lilielkhalil_project pull request #4
Opened 2021-07-29 19:03 UTC by lilielkhalil

Hello,

Kindly find my first try for git

2021-07-29 19:10 UTC, lilielkhalil commented
Hello, Kindly find my article below

2021-07-29 20:14 UTC, pbellec commented
thanks @lilielkhalil could you please move this text in the README.md file? That's what is rendered as your project home page.

Also please add a few sentences on your research interests and your background.

2021-07-30 14:50 UTC, pbellec requested changes

2021-07-30 14:50 UTC, pbellec commented on article.md
> +Born in 03 august 1998, my birthday is in 4 days !!
haha! Good to know!! I am going to let people know on discord. But I suggest to remove your exact birthday from this document. It is silly, but birthday is a security question in many services, so you should not make this information too easy to find on the web.

2021-07-30 14:50 UTC, pbellec commented on article.md
> +My status in Canada is as an International student
Once again, I suggest removing this type of personal information from a public document.

2021-07-30 14:50 UTC, pbellec commented on article.md
> +I do have more as administratif and finance experience.
suggestion: I had experience in administration and finance

2021-07-30 14:50 UTC, pbellec commented on README.md
>     <img src="https://avatars.githubusercontent.com/u/1670887?v=4?s=100" width="100px;" alt=""/>
you need to update this information

2021-07-30 14:50 UTC, pbellec commented on README.md
> +Hello, This is my first article
consider removing. Also I commented on the wrong document by mistake. See my comment in the other file.

2021-07-30 14:50 UTC, pbellec commented on article.md
> +Hello,
please remove this file, which has duplicate information with the readme.

2021-07-30 15:12 UTC, lilielkhalil commented
Bonjour,

Les changements a été faite maintenant avec succés

Mercii
Lili
________________________________
From: Pierre Bellec ***@***.***>
Sent: 30 July 2021 17:51
To: PSY6983-2021/lilielkhalil_project ***@***.***>
Cc: Lili El Khalil ***@***.***>; Mention ***@***.***>
Subject: Re: [PSY6983-2021/lilielkhalil_project] Iss1b (#4)


@pbellec requested changes on this pull request.

________________________________

In article.md<https://github.com/PSY6983-2021/lilielkhalil_project/pull/4#discussion_r679983663>:

>  My name is lili el khalil
-Master student at UdeM
+Born in 03 august 1998, my birthday is in 4 days !!


haha! Good to know!! I am going to let people know on discord. But I suggest to remove your exact birthday from this document. It is silly, but birthday is a security question in many services, so you should not make this information too easy to find on the web.

________________________________

In article.md<https://github.com/PSY6983-2021/lilielkhalil_project/pull/4#discussion_r679983994>:

>  My name is lili el khalil
-Master student at UdeM
+Born in 03 august 1998, my birthday is in 4 days !!
+My status in Canada is as an International student


Once again, I suggest removing this type of personal information from a public document.

________________________________

In article.md<https://github.com/PSY6983-2021/lilielkhalil_project/pull/4#discussion_r679984514>:

>  My name is lili el khalil
-Master student at UdeM
+Born in 03 august 1998, my birthday is in 4 days !!
+My status in Canada is as an International student
+
+Educational backgroung
+
+Till present : i'm doing my masters in psychology at UdeM
+I Did my bachelor in clinical psychology in Lebanon and i wish to continue my doctorate in Canada also in clinical psychology
+
+Working Experience :
+
+I Can say that i totally work in a different field than my study !
+I do have more as administratif and finance experience.


suggestion: I had experience in administration and finance

________________________________

In README.md<https://github.com/PSY6983-2021/lilielkhalil_project/pull/4#discussion_r679985467>:

> @@ -3,3 +3,24 @@
    <img src="https://avatars.githubusercontent.com/u/1670887?v=4?s=100" width="100px;" alt=""/>


you need to update this information

________________________________

In README.md<https://github.com/PSY6983-2021/lilielkhalil_project/pull/4#discussion_r679985979>:

> @@ -3,3 +3,24 @@
    <img src="https://avatars.githubusercontent.com/u/1670887?v=4?s=100" width="100px;" alt=""/>
    <br /><sub><b>Pierre bellec</b></sub>
 </a>
+
+Hello, This is my first article


consider removing. Also I commented on the wrong document by mistake. See my comment in the other file.

________________________________

In article.md<https://github.com/PSY6983-2021/lilielkhalil_project/pull/4#discussion_r679986229>:

> @@ -0,0 +1,26 @@
+Hello,


please remove this file, which has duplicate information with the readme.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/PSY6983-2021/lilielkhalil_project/pull/4#pullrequestreview-719156257>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AU7JZB2N6JOY4ZOC7RVX3QTT2K35XANCNFSM5BHB6PQQ>.

2021-07-30 15:51 UTC, pbellec commented
It still looks like the avatar on this branch is my picture. 
But I see this was updated on the main branch.
So it should get automatically merged, let's try!

2021-07-30 15:51 UTC, pbellec approved these changes

2021-07-30 15:52 UTC, merged